### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by julianfegert** [Performave/convoy#101]
### Current Behavior

There are issues in relation to the gdpr

### Expected Behavior

google fonts and scripts should be integrated locally and the option to activate a cookie consent tool

### Steps to Reproduce

-

### Proxmox OS Version

8.0

### Operating System

Ubuntu 22

### Browser

Chrome

### Panel Version

latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ericwang401** [comment]
Fonts will be sourced locally in the next major release (v5).

The cookie consent isn't necessary. I don't have anything that will need it.
