### ISSUE TITLE
Reseller access (feature request)

### ISSUE THREAD

**Issue by bitUpsurge** [Performave/convoy#106]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Reseller access for resellers and users with quota

### Describe the solution you'd like.

I would like to see a reseller access feature where we can assign users as resellers and they can create VMs in their assigned quota such as vCPUs, Storage and RAM allocated to their reseller account etcetera.

**Comment by ericwang401** [comment]
Ok this feels like a massive request in terms of modifying the data structures and the frontend to support this request.

How much requested is a feature like this? What am I getting in revenue for implementing something like this?

**Comment by staalexa** [comment]
in contrast to single user roles, i see a higher weight on having user roles as in #96. In Gerneral the option between admin/user is the most important issue. Being able to give users only certain permissions or even user groups, would fix most issues. The reselling stuff can be handled with minimal external code using convoy API, if we have more flexibility with single user permissions.

**Comment by bitUpsurge** [comment]
> Ok this feels like a massive request in terms of modifying the data structures and the frontend to support this request.
> 
> How much requested is a feature like this? What am I getting in revenue for implementing something like this?

Understandable, it's better to do this later when there's something in for you as well since it's going to cost a lot of time and restructuring.

Pardon me if it was a waste of time.
