### ISSUE TITLE
Add traffic quota limit for VMs

### ISSUE THREAD

**Issue by julianfegert** [Performave/convoy#107]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add traffic quota limit for VMs

### Describe the solution you'd like.

Setting for the Amount of Traffic that can be used by a VM for example every VM gets 2 TB per month. If the VM exceeds the Limit it gets lower bandwith rate or suspended

**Comment by ericwang401** [comment]
Yeah this exists already. Set a bandwidth limit on the servers you want to impose it on.

**Comment by julianfegert** [comment]
the field bandwith by creating a server is for this? 

or is this for the speed limit of the connection (mb/s)?

i want to configure if the vm exceeds 2 tb of monthy traffic it gets suspended
