### ISSUE TITLE
[FEATURE] Add user fetching via LDAP

### ISSUE THREAD

**Issue by GunniBusch** [Performave/convoy#109]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Would it be possible to fetch the users via ldap? This would allow, a more unified integration in existing management panels. 

### Describe the solution you'd like.

N/a

**Comment by ericwang401** [comment]
If you can describe a technical implementation of LDAP with the existing Users table, I can look into implementing this.

**Comment by GunniBusch** [comment]
Yeah I can look into it. But not in the near future. I will close it and reopen if I have time.
