### ISSUE TITLE
Fro's Suggestions

### ISSUE THREAD

**Issue by AnushK-Fro** [Performave/convoy#11]
1. ✅ Add an option to set the Cloudinit password, hostname, and nameservers before server creation so that it gets  automatically inserted and the server is ready to go (very useful for the API to automatically set everything for the client with info from WHMCS)
2. ✅ When filling out the new server form to add a new server, add a checkbox to automatically start the server once the creation is done 
3. ✅ Add an ISO library which lists the ISO's that are located in Proxmox and mounts them if the user requests it
4. ✅ Allow administrators to select the storage that backups are located and a separate storage where ISO's are located. Many hosts have separate servers for offsite backups + ISO storage, and many hosts use PBS to back up Proxmox VM's.
5. ✅ Allow node groups so that administrators can group nodes together (like the location option in Pterodactyl). A VM should be deployed on the node which has the least usage on each node group.
6. Allow IP's to be part of a pool, and allow IP/IP pools to be assigned to multiple servers. This is useful for hosts with a lot of IP's and nodes.

**Comment by ericwang401** [comment]
this is a shopping list

**Comment by AnushK-Fro** [comment]
7. Allow mass adding of IPv4 and IPv6 addresses (i.e. let's say I wanted to add all of the IP's between 45.61.161.2 to 45.61.161.250, right now I have to make a custom script or manually add them one by one)

**Comment by AnushK-Fro** [comment]
8. List the Convoy server ID in the administrator panel

**Comment by AnushK-Fro** [comment]
9. When putting in just a hostname but leaving out the nameservers, it sets the nameservers to just a comma which can break the network configuration depending on the OS

**Comment by AnushK-Fro** [comment]
10. Remove the comma between nameservers, for some reason it's not supported on Ubuntu 22.04, will have to find a workaround to that.

**Comment by AnushK-Fro** [comment]
11. Update the server name in Proxmox to the hostname, would be much easier to identify servers without having to go to Convoy and check.

**Comment by AnushK-Fro** [comment]
12. ~~Update command displayed in nodes tab (to install the noVNC broker) to CD to the root directory first (minor change)~~

**Comment by AnushK-Fro** [comment]
13. Allow the removal of servers that don't exist in Proxmox (force remove option) and an option to remove a server without deleting it from Proxmox

**Comment by AnushK-Fro** [comment]
14. VM's without an IP produce a Laravel error page when trying to go into server settings (MAC Address error)

**Comment by AnushK-Fro** [comment]
15. Option to delete backups on VM deletion to save on space

**Comment by AnushK-Fro** [comment]
16. Check if the IP is a duplicate and make sure that the user doesn't accidentally add 2 of the same duplicate IP's.

**Comment by AnushK-Fro** [comment]
17. I haven't investigated this issue much, but it appears that some servers will get stuck on building permanently and I can't remove them without going into the DB. Would be nice to implement some sort of timeout or handling of errors to either prompt the user or offer to remove them

**Comment by AnushK-Fro** [comment]
18. Ability to mass delete, suspend, unsuspend, and mass create servers with the same configurations

**Comment by ericwang401** [comment]
> 13. Allow the removal of servers that don't exist in Proxmox (force remove option) and an option to remove a server without deleting it from Proxmox

The latter is already present, and you should be able to remove servers that don't exist
