### ISSUE TITLE
Multi-Node usage for Convoy Extension on Paymenter

### ISSUE THREAD

**Issue by julianfegert** [Performave/convoy#110]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When you create a product in Paymenter, you can only select one host in the Convoy extension for paymenter. If this host is fully booked, an error appears: exceeds the nodes limit. 

The Convoy extension for paymenter should use the next free host if several hosts are stored in Convoy.

### Describe the solution you'd like.

For example, 2 hosts are stored in Convoy, e.g. pve06 and pve08. The convoy extension for paymenter is set to pve06. pve06 is fully utilized, then the extension should not issue an error but create the vm on pve08. an error message should only be issued if there is no free capacity on any existing node.

**Comment by TeYroXOfficial** [comment]
You should open an issue in Convoy extension for Paymenter repo, instead of here. 
Eric didn't wrote extension for it.

**Comment by julianfegert** [comment]
I already have. But I thought it might be necessary to make adjustments to convoy as well. 
or can such a feature conpletely realized via adaptations to the extension without edits on convoy?

**Comment by Adekabang** [comment]
For now you can copy the extension and rename it. So, you have 2 or more extension, and choose the node. Then create a new product. This is the temporary solution. and also don't forget to set the stock.

**Comment by ericwang401** [comment]
Modifying Convoy to support Paymenter's inability to load balance between many nodes would break other extensions that have implemented this ability.
