### ISSUE TITLE
VM Hostnode change

### ISSUE THREAD

**Issue by julianfegert** [Performave/convoy#112]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add a feature that the host node can be changed. 

### Describe the solution you'd like.

If I backup a VM and transfer the Backup to another hostsystem and create a new entry (untick create server) in convoy, the paymenter extension doesnt removes the new (transferred) server if the billing date is exceed. 

it should be able to transfer the backup from a node e.g pve06 to pve08 and only replace the node in the existing server control of the vm in convoy. convoy then should found the vm on the other node by vm id.

**Comment by ericwang401** [comment]
Convoy will not do this. This is more of a manual process than automatic–for now, at least.

1. You need to verify that the snapshots/backups for a vm is accessible on the new node
2. You need to check that the allocated IPs are accessible on the new node.
3. You need to make sure there is enough resources to make the transfer (e.g., snapshots, backups, cpu, memory, disk space for the vm)
