### ISSUE TITLE
Disable SLAAC by default on cloudinit

### ISSUE THREAD

**Issue by BradPerbs** [Performave/convoy#122]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Would be good to know how to disable SLAAC by default in the cloud init.

### Describe the solution you'd like.

Option to enable or disable slaac

**Comment by ericwang401** [comment]
In the technical details of this feature request, could you elaborate on how SLAAC could be disabled, what SLAAC is, and its importance?

**Comment by BradPerbs** [comment]
to disable it:  in the netplan config it should add a row   `accept-ra: false`

It's quite important otherwise you get router announced unwanted ipv6 on the vm's.

**Comment by BradPerbs** [comment]
`accept-ra: false` can be sent through the cloud init as well, but it's not clear where in convoy should be added, when I try to add it it breaks the vm configuration

**Comment by ericwang401** [comment]
> `accept-ra: false` can be sent through the cloud init as well, but it's not clear where in convoy should be added, when I try to add it it breaks the vm configuration

I don't see how it is possible, given Proxmox's APIs, for Convoy to make this change.

**Comment by staalexa** [comment]
> SLAAC

The user can still 
1. disable cloudinit
2. set the netplan config manually (cloud init only runs during boot)

Therefore, doing it via cloudinit is not the best choice anyway. Another solution needs to be found to fix this.

**Comment by ericwang401** [comment]
Closing to inactivity
