### ISSUE TITLE
Editing VM = Additional Resources

### ISSUE THREAD

**Issue by CloudieLLC** [Performave/convoy#16]
Proxmox: 7.3-3
Convoy: v3.6.2-beta

Expected: To update Server bandwidth limitations. 

What it does: Requires additional Disk Space
(yes, I've got it on a small segment of a proxmox server, so i don't munt things) 

Pictures: 
https://my.screenimg.xyz/18731331
https://my.screenimg.xyz/8f87776f
https://my.screenimg.xyz/0f634ad1

When changing nothing to do with disk, it requires more disk space (and would assume it would do the same with RAM if i had it closer to it's no-sell point) 

But, simple edit of something that doesn't matter to the resources of RAM and Disk, shouldn't require extra RAM/Disk available.

**Comment by ericwang401** [comment]
Convoy isn't requiring additional resources. It appears like it falsely determined that there wasn't enough resources on the node to allocate to the VM. I will have to try to replicate this bug.

**Comment by ericwang401** [comment]
The issue was because Convoy calculated the incorrect amount of available resources. Convoy would leave in the current server's allocation in the calculation instead of subtracting it, inflating the total used resources.

**Comment by ericwang401** [comment]
Resolved in https://github.com/ConvoyPanel/panel/releases/tag/v3.7.0-beta
