### ISSUE TITLE
Feature Request: Reverse DNS via.....

### ISSUE THREAD

**Issue by CloudieLLC** [Performave/convoy#17]
Ability to have hosted PowerDNS, PowerDNS Admin or even using Cloudflare etc

Or, inbuilt with ability to push out via AFXR or something, but.. having rDNS ability would be good :) (unless i've missed where that is)

**Comment by ericwang401** [comment]
Hello, thank you for your feature request.

I do not have an idea of how I would implement rDNS into Convoy. Would users already have the ability to do it through their registrar or alternative providers (e.g. no-ip)? What unique benefit does this feature bring?

**Comment by CloudieLLC** [comment]
users themselves, no. since it would be tied by the provider, since it's their IP space, would then need to setup a DNS server anyway ( PowerDNS, BIND etc) , or offload it to Cloudflare, or CloudNS etc. and use API to set the reverse dns (PTR) for users. 

Especially for those that are running mail servers or simular on their VMs, having proper reverse dns (PTR) is best. 

eg; Without PTR: https://my.screenimg.xyz/920a748f
eg; With PTR: https://my.screenimg.xyz/e4151ec3

Which, if you were able to add in an API call function, using Cloudflare or CloudNS and say PowerDNS. (with options) then things would be able to work from that;

on how it's made in other panels; `https://docs .virt fusion.com/administration/reverse-dns`

**Comment by ericwang401** [comment]
> users themselves, no. since it would be tied by the provider, since it's their IP space, would then need to setup a DNS server anyway ( PowerDNS, BIND etc) , or offload it to Cloudflare, or CloudNS etc. and use API to set the reverse dns (PTR) for users.
> 
> Especially for those that are running mail servers or simular on their VMs, having proper reverse dns (PTR) is best.
> 
> eg; Without PTR: https://my.screenimg.xyz/920a748f eg; With PTR: https://my.screenimg.xyz/e4151ec3
> 
> Which, if you were able to add in an API call function, using Cloudflare or CloudNS and say PowerDNS. (with options) then things would be able to work from that;
> 
> on how it's made in other panels; `https://docs .virt fusion.com/administration/reverse-dns`

This is interesting. I will have to take another look at this at another time. I am busy with making Convoy stable and performant as it is at the moment. I hope you can understand. Thanks!

**Comment by CloudieLLC** [comment]
I more than understand, as I go through and do more testing, I might come up with some more FR's and stuff, and of course, i'm open to been told to shut up :)

**Comment by ericwang401** [comment]
This request must be remade with the new feature request template.
