### ISSUE TITLE
Change Request: Modifying Convoy favicon and logo.

### ISSUE THREAD

**Issue by yatinmanuel** [Performave/convoy#22]
Favicon and Logo can be updated using either the solid-black svg or the gradient iteration.

![Convoy_BlackLogo](https://user-images.githubusercontent.com/92684524/233761894-dc8cc906-f457-41ef-a2d1-0fc157fe3e64.svg)

![Convoy_GradientLogo](https://user-images.githubusercontent.com/92684524/233761874-1dfd9336-d60e-434e-be11-087c6bc380c9.svg)

**Comment by ericwang401** [comment]
Is it okay if you can center the vector art and make the dimensions of the SVG have the width and height of the actual vector art? There is currently extra width and height.

Thanks!

**Comment by yatinmanuel** [comment]
Will do

**Comment by ericwang401** [comment]
Added in https://github.com/ConvoyPanel/panel/commit/6b1f29a22d2a0fc2a8ba91519c9319337b0ad264
