### ISSUE TITLE
remove server after create

### ISSUE THREAD

**Issue by urobasa** [Performave/convoy#25]
The server cannot be deleted.
The server was created in the interface, but it was not created in proxmox
After that, it cannot be removed from the interface and it is impossible to remove the node on which this non-removable server is located.

**Comment by ericwang401** [comment]
There were no logs provided.

Please run these commands to generate logs:

```
wget https://github.com/ConvoyPanel/log-collector/releases/latest/download/log_collector
chmod +x ./log_collector
./log_collector
```

**Comment by urobasa** [comment]
https://paste.frocdn.com/upuyefapok
