### ISSUE TITLE
Can't delete server after creation

### ISSUE THREAD

**Issue by urobasa** [Performave/convoy#26]
The server created in the web interface, it is not created in proxmox
After that, it cannot be removed from the interface and it is impossible to remove the node on which this no-delete server is located.
Api user created, add to variables secret
Is it possible to set up a convoy with an already existing Proxmox cluster, or should the cluster be new with only cluster nodes and no virtual machines?
I am using an existing cluster with previously created virtual machines through the proxmox web interface and I do not see them in the convoy interface.

https://paste.frocdn.com/upuyefapok

**Comment by urobasa** [comment]
version 3.8.1-beta
### access.log pveproxy
root@pam!convoy_panel [02/06/2023:22:40:14 +0300] "GET /api2/json/nodes/asusnode0/qemu/853887097/config HTTP/1.1" 500 13

proxmox task - download:debian-11.7.0-amd64-netinst.iso:root@pam!convoy_panel: 6475ECAE OK
successfully

:qmstop:853887097:root@pam!convoy_panel: 6475F038 unable to find configuration file for VM 853887097 on node XXX

**Comment by ericwang401** [comment]
Please see if updating to the latest version of Convoy resolves this issue

**Comment by urobasa** [comment]
upgaded panel to latest
The server created in the web interface, it is not created in proxmox
After that, it cannot be removed from the interface and it is impossible to remove the node on which this no-delete server is located.

**Comment by urobasa** [comment]
To create a virtual machine in proxmox over panel convoy, a template must exist, the number of which must be specified in the convoy template group.
This information is missing from the documentation.

**Comment by ericwang401** [comment]
I can't really understand what you are saying. Sorry.

**Comment by urobasa** [comment]
We will wait for the release and clarification of the documentation for use.
close issue
