### ISSUE TITLE
WHMCS Module (Billing)

### ISSUE THREAD

**Issue by bitUpsurge** [Performave/convoy#27]
Hey there,

I see Convoy has a Blesta Module, wouldn't it be better if it had a WHMCS module too as it's the most popular web hosting automation software currently that way Convoy will get more users and generate more revenue as well.

Cordially,
Abdullah Jamal

**Comment by ericwang401** [comment]
Someone else is working on it in the Discord community. Please ask adly#7888 for updates related to a WHMCS billing module. Thanks!
