### ISSUE TITLE
VPS Rebuild Option (Feature Request)

### ISSUE THREAD

**Issue by bitUpsurge** [Performave/convoy#28]
Hey there,

It would be great if we can rebuild our VPSes Incase of an error or we need to completely wipe out the VPS and reinstall it with the same OS or with a different one.

Cordially
Abdullah Jamal

**Comment by ericwang401** [comment]
Can you please elaborate on how this will be different from the reinstall feature I have in the panel right now?

**Comment by bitUpsurge** [comment]
Hey,

My bad there, I haven't used the panel yet so I didn't knew as it wasn't specified in Website or GitHub, one suggestion create a features page on website ;).

Cordially,
Abdullah Jamal
