### ISSUE TITLE
Upgrade/Downgrade Option (Feature Request)

### ISSUE THREAD

**Issue by bitUpsurge** [Performave/convoy#29]
Hey there,

It would be great to see upgrade and downgrade of VPS feature in Convoy Panel Incase of huge traffic or intensive needs due to high customer traffic on the services etc or if we change our mind and need to downgrade to a lower specification.

Cordially,
Abdullah Jamal

**Comment by ericwang401** [comment]
I don't know what you want me to add. Can you be more specific?

**Comment by bitUpsurge** [comment]
Hey,

A feature where we downgrade and upgrade VPS by changing their Memory Storage and Disk as we like without wiping the data of VPS.

Cordially,
Abdullah Jamal

**Comment by ericwang401** [comment]
> Hey,
> 
> A feature where we downgrade and upgrade VPS by changing their Memory Storage and Disk as we like without wiping the data of VPS.
> 
> Cordially, Abdullah Jamal

You can change the memory in the Convoy interface, but it is not possible to change the disk size. Changing the disk size may result in DATA LOSS.

You can use the Convoy application API to change CPU and memory allocations. However, the server must be restarted to make the changes persist.

As a hosting company, I wouldn't add this feature as you may have to explain to frustrated customers why their data is corrupted or lost. This would damage your reputation as a reliable provider, but I am not one to to stop you from adding it anyways. If you want, you can fork the repository and add it :)

**Comment by ericwang401** [comment]
Sorry, I would like to clarify about changing the disk size. You cannot DECREASE the disk size without the possibility of data loss.

**Comment by bitUpsurge** [comment]
> Sorry, I would like to clarify about changing the disk size. You cannot DECREASE the disk size without the possibility of data loss.

I understand but it would be great if we are able to change CPU as well.

**Comment by ericwang401** [comment]
> 

You can change the CPU from Convoy. You just have to restart or kill the server to make the change persist.

**Comment by as202400** [comment]
For these functions, you may just use Convoy API to do it yourself. In my case, my team built a SaaS and used convoy as the panel with hour billing and sync single site login. And also allow the user to upgrade or degrade their VM. In the disk, we only allow end user UPGRADE.

**Comment by bitUpsurge** [comment]
> For these functions, you may just use Convoy API to do it yourself. In my case, my team built a SaaS and used convoy as the panel with hour billing and sync single site login. And also allow the user to upgrade or degrade their VM. In the disk, we only allow end user UPGRADE.

Then what's the purpose of fully functional VPS panel if it lacks some features which can be done using API only?

**Comment by ericwang401** [comment]
> 

You can change the CPU amount from the Convoy interface

![image](https://github.com/ConvoyPanel/panel/assets/37554696/5bda5edd-8451-4eb7-acab-01bbe2708497)

**Comment by bitUpsurge** [comment]
Oh my bad, sorry, didn't knew it.
