### ISSUE TITLE
Backups/Snapshots (Feature Request)

### ISSUE THREAD

**Issue by bitUpsurge** [Performave/convoy#31]
Hey there,

It would be great to have Backups and Snapshots feature where users would be able to backup their servers and take snapshots whether they're onsite or off-site, although off-site is always better and considered as onsite would make the Hypervisor full.

Cordially,
IoniqPace Administration

**Comment by ericwang401** [comment]
Can you please stop creating suggestions without using Convoy?

**Comment by bitUpsurge** [comment]
Sorry my bad, I'll get it installed now and test it.
