### ISSUE TITLE
Bare Metal Servers (Feature Request)

### ISSUE THREAD

**Issue by bitUpsurge** [Performave/convoy#32]
Hey there,

It would be great to see the possibility of creating Bare Metal/Dedicated Servers and managing them through Convoy like SynergyCP etc.

Cordially,
IoniqPace Administration

**Comment by ericwang401** [comment]
You can do this by allocating the entire node's resources to a single server. It's not possible to manage bare metal servers with Proxmox, the virtualization software Convoy uses.

Hope this answers the question.

**Comment by bitUpsurge** [comment]
Hey there,

The problem with allocating whole node is that it's still a VPS with KVM Hypervisor it isn't a dedicated server so software will not be supported that requires a truly dedicated machine, Convoy can use Proxmox for VPS and custom Dedicated Server integration it'll make convoy a all in one panel and generate more revenue.

Cordially,
Abdullah Jamal

**Comment by ericwang401** [comment]
> Hey there,
> 
> The problem with allocating whole node is that it's still a VPS with KVM Hypervisor it isn't a dedicated server so software will not be supported that requires a truly dedicated machine, Convoy can use Proxmox for VPS and custom Dedicated Server integration it'll make convoy a all in one panel and generate more revenue.
> 
> Cordially,
> Abdullah Jamal

Yes, it wouldn't be possible to manage bare metal servers with Proxmox, so I wouldn't be able to add this type of feature to Convoy either.
