### ISSUE TITLE
Feature request: Multiple disks in a node

### ISSUE THREAD

**Issue by Adrip28** [Performave/convoy#34]
Possibility to add multiple disks per node and choose the one with more free space (in %) to create the VM to balance the space between disks.

**Comment by ericwang401** [comment]
I don't think I can add this into Convoy, but you can already do this with Proxmox with RAID and a ZFS pool

See https://forum.proxmox.com/threads/add-multiple-disks-to-single-node-proxmox.109684/ and https://forum.proxmox.com/threads/proxmox-ve-with-multiple-hard-drives.51288/

Check this out for more resources beyond the two links I provided https://www.google.com/search?q=proxmox+multiple+disks
