### ISSUE TITLE
Feature Request: SSO login through generic IDP  

### ISSUE THREAD

**Issue by tawfekk** [Performave/convoy#39]
Feature to allow users to login using a custom SAML and/or OIDC provider. 

This would make it possible to use an existing central userbackend (Authentik, Active Directory, Keycloak etc.) instead of having to provision new users manually in Convoy.

**Comment by ericwang401** [comment]
This feature isn't my priority at the moment. I am backlogged, so this request will be reconsidered in ~6 months.

Thanks for your understanding!

**Comment by ericwang401** [comment]
This request must be remade with the new feature request template.
