### ISSUE TITLE
Type on "Add Node" section

### ISSUE THREAD

**Issue by leo852** [Performave/convoy#42]
![image-1.png](https://github.com/ConvoyPanel/panel/assets/33802295/0c187f64-6e5c-494b-9cd8-774d0ceba226)

There are two "Disk Allocation" in the list

**Comment by ericwang401** [comment]
Thanks for the report! This issue has been resolved in commit d8618cbe748e2c91cc7e75fc8647e88252479819.

This fix will be pushed in the v4 release
