### ISSUE TITLE
Branding Functions Suggestions

### ISSUE THREAD

**Issue by leo852** [Performave/convoy#43]
1. Recommended to add easy branding such as easy logo and footer replacement.

2. Multi-Domain support, allow user to use multiple domains to access the panel. Maybe it could also apply to the 1 suggestion, which is different domain will show different logo and footers. 

3. Alternative color replacement will also be good, for example, changing the dark mode color to grey/dark blue using color code.

**Comment by staalexa** [comment]
If you are using the panel for hosting and know what you are doing as a serious server provider, it does not take longer than 5 minutes to change the logo and footer :) Same applies for the colors.

**Comment by leo852** [comment]
> If you are using the panel for hosting and know what you are doing as a serious server provider, it does not take longer than 5 minutes to change the logo and footer :) Same applies for the colors.

I know it's not hard, but these are just "suggestions" for easier setup.

**Comment by ericwang401** [comment]
Sorry, I'm not planning on adding this.
