### ISSUE TITLE
Adding option "don't touch network" for creating server that follows template original option (dhcp)

### ISSUE THREAD

**Issue by leo852** [Performave/convoy#44]
![image](https://github.com/ConvoyPanel/panel/assets/33802295/53c04baa-92e2-4975-8a7a-42fc4e768c93)
Will you consider adding "don't touch network" so the new server could follow proxmox cloud-init template to use dhcp or slacc?

**Comment by ericwang401** [comment]
Please describe the implementation in complete detail.

**Comment by ericwang401** [comment]
Closing this because not enough information was provided.
