### ISSUE TITLE
Confusing rounding of disk space

### ISSUE THREAD

**Issue by ItzExotical** [Performave/convoy#45]
Convoy rounds disk space >.49 to the next integer.
In this following example, the VM actually has 1.5 TiB and not 2 TiB (displayed by panel):
![image](https://github.com/ConvoyPanel/panel/assets/93738720/59fc4e3d-c33d-4bac-a8e7-9d870a62e553)
This is a bit confusing for customers as 1.5 TiB and 2 TiB is a 500 GIB difference.

**Comment by ericwang401** [comment]
I wasn't able to reproduce this bug. If this issue still persists, provide reproduction steps in a new bug report.
