### ISSUE TITLE
NAT VM Deployment

### ISSUE THREAD

**Issue by Hostrdp** [Performave/convoy#57]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Ability to auto deploy NAT VM using NAT IP that assigned on the node
Ability to auto configure port forwarding (SSH if Linux, RDP if Windows + HTTP and HTTPS ports) and assigns 20 ports for usages

### Describe the solution you'd like.

Maybe using combinations Proxmox API and Iptables scripts

**Comment by ericwang401** [comment]
How will port forwarding work exactly if a port that is needed among all the VMs can only be allocated to a single VM?

**Comment by TeYroXOfficial** [comment]
For example VM will get 20 ports, let's say from 59200->59220, so first port of this range will be set to 22/3389 of vm internal

For example:
iptables -t nat -A PREROUTING -i vmbr0 -p tcp --dport 59200 -j DNAT --to 192.168.100.1:22

Where 192.168.100.1 is a local IP's are assigned from NAT IP block

**Comment by ericwang401** [comment]
There seems to be a load of work cut out for this to be implemented, which is something above my pay grade.
