### ISSUE TITLE
Convoy does not use the correct storage location

### ISSUE THREAD

**Issue by staalexa** [Performave/convoy#64]
### Current Behavior

Convoy does not use the correct storage location

### Expected Behavior

Convoy shall use the correct storage location

### Steps to Reproduce

define storage x in node settings of convoy. Create a server. See how the server is always sent to "local" and not the defined one.

### Screenshots

@ericwang401 has them

### Proxmox OS Version

8.0.4

### Operating System

Windows, Linux

### Browser

Any

### Panel Version

3.10.1-beta

### Error Logs

https://paste.frocdn.com/ebejubiper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ericwang401** [comment]
Patched in v3.10.2-beta and v4.0.0-rc.2
