### ISSUE TITLE
Unable to deploy instance if IPv6 is selected in the "Create a server" page.

### ISSUE THREAD

**Issue by leo852** [Performave/convoy#65]
### Current Behavior

Throws an error and create an instance on convoy but proxmox is untouched (So the instance is actually created).
![Screenshot_2023-12-18_105152](https://github.com/ConvoyPanel/panel/assets/33802295/0abdc2eb-ade0-4f6f-b8ac-6e8580dece1f)

### Expected Behavior

Create an instance on both convoy and proxmox

### Steps to Reproduce

Add IPv6 to IPAM and select that address during "Create a server"

### Proxmox OS Version

8.1.3

### Operating System

Windows 11

### Browser

FIrefox

### Panel Version

4.0.0-rc2

### Error Logs

https://paste.frocdn.com/idibusucun

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ericwang401** [comment]
Patched in [v4.0.0-rc.3](https://github.com/ConvoyPanel/panel/releases/tag/v4.0.0-rc.3)
