### ISSUE TITLE
IPv6 Bulk import not working

### ISSUE THREAD

**Issue by leo852** [Performave/convoy#66]
### Current Behavior

Shows error when import multiple ipv6
![image-1](https://github.com/ConvoyPanel/panel/assets/33802295/60ea46e3-057d-4b1d-9a1e-6797e10ed07c)

### Expected Behavior

Import multiple ipv6 address 

### Steps to Reproduce

Import multiple ipv6 in IPAM page

### Proxmox OS Version

8.1.3

### Operating System

Windows/Android 

### Browser

Firefox

### Panel Version

4rc3

### Error Logs

https://paste.frocdn.com/eletivucut

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by leo852** [comment]
Btw, I'll recommend setting default subnet for iPv6 to 64 as normally the minimal subnet for end-user should be /64

**Comment by ericwang401** [comment]
Fixed in v4.0.0-rc.4
