### ISSUE TITLE
Lock VM on VM suspension

### ISSUE THREAD

**Issue by AnushK-Fro** [Performave/convoy#69]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Currently, when a VPS is suspended, it is just stopped. Preferably, upon VPS suspension, it should lock the VM configuration or do something similar in order to ensure that the VPS does not get booted back online if there is a mass node reboot or something similar.

### Describe the solution you'd like.

Either lock the VM configuration, or check the suspended VM's on a cron job or similar and re-stop the VPS's.

**Comment by ericwang401** [comment]
how do I lock it?

**Comment by JouanDeag** [comment]
You may pause the VM and disable start on boot.

**Comment by ericwang401** [comment]
> You may pause the VM and disable start on boot.

Start at boot is disabled by default, so it wouldn't work in this case. But thank you for the suggestion.

**Comment by ericwang401** [comment]
Not enough info
