### ISSUE TITLE
Bug with bandwidth limit

### ISSUE THREAD

**Issue by Moi045** [Performave/convoy#70]
### Current Behavior

When i go to create a VM, in the bandwidth limit field, i put the bandwidth for example i want 6TB, i put 6291456 that its equivalent to 6TB, in the moment when the vm its creating, i check the bandwidth limit and its in 6MB (only has the first number)

### Expected Behavior

That the bandwidth limit are set correctly when you put the number

### Steps to Reproduce

Create a VM normally, and set any bandwidth limit in the bandwidth field, and when the install its finished, check the bandwidth limit, that only has the first number instead of all bandwidth numbers

### Screenshots

![screenshot1](https://github.com/ConvoyPanel/panel/assets/79182615/45a785f9-6134-451d-885c-6e5dcfa583c8)
![screenshot2](https://github.com/ConvoyPanel/panel/assets/79182615/193f4ddb-c235-4c5e-ba09-97c07c063cec)

### Proxmox OS Version

8.1.3

### Operating System

Ubuntu 22.04

### Browser

N/A

### Panel Version

4.0.0-rc.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ericwang401** [comment]
Fixed in 62c5193 and is scheduled for release with `v4.0.0-rc.6`
