### ISSUE TITLE
Special character detection issues in panels

### ISSUE THREAD

**Issue by wjy20030407** [Performave/convoy#80]
### Current Behavior

When installing/reinstalling a system for a VM,
typing `~ in System OS Password prompts Invalid english_keyboard_characters,
typing ()-_=+[{]}\|;:'",<. >/? is not recognized as a special character.

It also appears when creating user passwords.

### Expected Behavior

Ability to correctly match special characters.

### Steps to Reproduce

When installing/reinstalling VMs and creating/changing user passwords.

### Proxmox OS Version

8.1.4

### Operating System

Windows 11 23H2

### Browser

Chrome 122

### Panel Version

4.2.2-rc.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ericwang401** [comment]
Should be patched in the upcoming v4.2.3-rc.1 release
