### ISSUE TITLE
Networking issue

### ISSUE THREAD

**Issue by cloudrack-ca** [Performave/convoy#83]
### Current Behavior

Create a vm via convoypanel i.e ubuntu images 18 - 20 - 22 you will get an issue for ipv4 not connecting 

for some reason on creation of the VM itself its missing the 

```
            routes:
            -   on-link: true
                to: default
                via: xxx.xxx.xxx.xxx
            set-name: eth0
```

via the `/etc/netplan/50-cloud-init.yaml` inside of the VM that was created.

I have to manually go in and add this into every VM created from convoypanel......

### Expected Behavior

ping google.com -4 

to actually work i.e port 22 being accessible to world.

### Steps to Reproduce

explained below

### Screenshots
![image](https://github.com/ConvoyPanel/panel/assets/145787423/b27fba78-26dd-4a81-a349-98669672bdc2)
![image](https://github.com/ConvoyPanel/panel/assets/145787423/5d5cad7c-ba34-424c-905b-44b6d473005a)
---
![image](https://github.com/ConvoyPanel/panel/assets/145787423/10dffe94-865b-4dee-bc2c-c210b20f16d4)
![image](https://github.com/ConvoyPanel/panel/assets/145787423/7ca7c784-dbeb-4d0c-9517-23bf701272d1)

### Proxmox OS Version

8.1.4

### Operating System

Bookworm

### Browser

Edge - Always Latest Non Dev Version

### Additional Context
Offering a means to set this via the convoypanel would be the simplest fix In my eyes,

but yes I'm not sure where the bug lies I'm still going to need some more time to try to pinpoint the matter but bringing to your attention @ericwang401 in hopes maybe you know the bug / issue / seen it before / know the fix / or hopefully addressing a first time 🐛 we can 👟(squash)

- network ipv4 gateways are correct netmasks are correct as well via convoypanel ipam and I've also setup macs for all the IP's 
- I create a VM from convoy using the pop-up menu (should have an add server button on home dash / user dash area for admin users as well make it easier to just create a VM instead of going into /admin everytime) once the VM creates I have it set to not auto start after creation. 
- i double check Hostname / DNS settings for cloudinit as well as ipv4 config all looks fine (normally does I continue)
- then I go and start the VM from convoypanel and open up a xTerm.js terminal or noVNC terminal i then wait for everything to load + cloud-init to run i.e to be able to login with desired password.
-  i then try to `ping google.com -4` right away to see if ipv4 is active....nothing
- i then go to `nano /etc/netplan/50-cloud-init.yaml` inside the VM and notice that the above aforementioned `routes` block is missing so i add it in and run a `netplan try` then a `netplan apply`  if confirmed to be runnable.
- i then again `ping google.com -4` and i get a connection on the VM using the IPv4 it was assigned 

Each server gets a Free IPv6 address to boot via our DHCPv6 protocols in place hence a connection on hop for ipv6 but nothing for ipv4 unless above is done.

### Panel Version

v4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cloudrack-ca** [comment]
im not sure if you understand my issue but during the cloud-init deployment on the VM that was created the `50-cloud-init.yaml` losses or never adds a `routes` block and adds `gateway4:` line instead as seen in screenshots.

(side note server name in images is named what it is `one-two-three-ha-ha-ha` cause at this point I'm losing my mind trying to find this darn 🐛 but I didn't dev convoy so I'm lost where to start looking) is it in the proxmox default `cloud-init` templating that needs to be addressed `per a node`? is it in convoy itself, can you also let me know what command or what is used to pull up a bug log for convoypanel? and if you would like to email me or if we can confirm secure communications I believe maybe I can hand off some credentials here and let you see the full configuration on my end offering more debugging from the convoypanel devs point of view.

**Comment by virtualized-human** [comment]
This has nothing to do with convoy. Convoy just uses default proxmox cloud-init deployment and does not change anything to the vm config.

**Comment by virtualized-human** [comment]
Solution 1: dont use ubuntu
Solution 2: make an ubuntu bug
or Solution 3: make a fixed template which dont have such issues. how you resolve this is up to you.

**Comment by ericwang401** [comment]
> im not sure if you understand my issue but during the cloud-init deployment on the VM that was created the `50-cloud-init.yaml` losses or never adds a `routes` block and adds `gateway4:` line instead as seen in screenshots.
> 
> (side note server name in images is named what it is `one-two-three-ha-ha-ha` cause at this point I'm losing my mind trying to find this darn 🐛 but I didn't dev convoy so I'm lost where to start looking) is it in the proxmox default `cloud-init` templating that needs to be addressed `per a node`? is it in convoy itself, can you also let me know what command or what is used to pull up a bug log for convoypanel? and if you would like to email me or if we can confirm secure communications I believe maybe I can hand off some credentials here and let you see the full configuration on my end offering more debugging from the convoypanel devs point of view.

This is a strange issue. I wonder if it is possible if I could remove netplan from the Ubuntu images.

As for `one-two-three-ha-ha-ha` that seems like your server's hostname, whoever set `one-two-three-ha-ha-ha` as the hostname is the value for `search` in the netplan configuration.

**Comment by ericwang401** [comment]
> Solution 1: dont use ubuntu Solution 2: make an ubuntu bug or Solution 3: make a fixed template which dont have such issues. how you resolve this is up to you.

Please be respectful even though that this isn't exactly relevant to Convoy. I don't want to promote a hostile environment.

**Comment by virtualized-human** [comment]
hm what isnt respectful there? its just facts i didnt blame anyone here :P

**Comment by cloudrack-ca** [comment]
> > im not sure if you understand my issue but during the cloud-init deployment on the VM that was created the `50-cloud-init.yaml` losses or never adds a `routes` block and adds `gateway4:` line instead as seen in screenshots.
> > (side note server name in images is named what it is `one-two-three-ha-ha-ha` cause at this point I'm losing my mind trying to find this darn 🐛 but I didn't dev convoy so I'm lost where to start looking) is it in the proxmox default `cloud-init` templating that needs to be addressed `per a node`? is it in convoy itself, can you also let me know what command or what is used to pull up a bug log for convoypanel? and if you would like to email me or if we can confirm secure communications I believe maybe I can hand off some credentials here and let you see the full configuration on my end offering more debugging from the convoypanel devs point of view.
> 
> This is a strange issue. I wonder if it is possible if I could remove netplan from the Ubuntu images.
> 
> As for `one-two-three-ha-ha-ha` that seems like your server's hostname, whoever set `one-two-three-ha-ha-ha` as the hostname is the value for `search` in the netplan configuration.

`search` under `one-two-three-ha-ha-ha` ran under search but comes from hostname under convoypanel right, but yes if there was a means to remove the netplan for the default templates so the community can have functioning ubuntu images, maybe workable.

**Comment by AnushK-Fro** [comment]
Out of curiosity, what hosting provider are you using? I believe the `routes` section should only be required for certain network configurations using routed setups I believe, hence why it's not in the default template.

I think you could try checking the Cloudinit config file and seeing if it's possible to do that automatically, otherwise, you could maybe do it through the host operating system depending on how your hosting provider does the network config.

**Comment by ericwang401** [comment]
Closing because not enough information
