### ISSUE TITLE
API api/application/servers 404

### ISSUE THREAD

**Issue by zbuse** [Performave/convoy#88]
### Current Behavior

rquest post to  api/application/servers  return 404

### Expected Behavior

Found the log when writing the whms module
     [message] => No query results for model [Convoy\Models\Node].

### Steps to Reproduce

curl   api/application/servers  return 404

### Proxmox OS Version

8.1

### Operating System

linux

### Browser

curl

### Panel Version

 4.2.2-rc.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by zbuse** [comment]
And wiki documentation is missing about running the php artisan horizon:work daemon

**Comment by ericwang401** [comment]
Did you make sure you specified the correct node?

Documentation isn't really needed for the Horizon daemon because the default Convoy installation runs the daemon. Are you tampering with the configuration?

**Comment by zbuse** [comment]
problem solved
