### ISSUE TITLE
some functional requirements

### ISSUE THREAD

**Issue by zbuse** [Performave/convoy#89]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

1.
Cancel setting template for each node
Move the template to the global management menu. All nodes only need to synchronize the template
and Add template import function

2.
Added "Virtual Machine Status", "Power On", "Shut Down", "Pause" and "Delete" buttons to the /admin/servers list

3. Add speed limit function
4. Increase IO usage statistics
5. Add bandwidth reset
6. Add node details to the node Overview page.
7.Added batch deletion function for server IP
8. Added batch startup and shutdown to the server list, and updated status

### Describe the solution you'd like.

Above contents

**Comment by zbuse** [comment]
And Add server migration node function

**Comment by zbuse** [comment]
Using nginx directory proxy coterm
FQDN https://panel.xxx.xxx/coterm/
the jump connection https://panel.xxx.xxx/coterm/:443/?type=novnc&token=
hope the code can be updated to support directory proxy

**Comment by zbuse** [comment]
Looking forward to adding coterm url to the interface to obtain /api/application/servers/<uuid>

**Comment by zbuse** [comment]
Request add node lock function

**Comment by zbuse** [comment]
Request  reinstall/updateBootOrder/mount iso function

**Comment by ericwang401** [comment]
There is very little explanation to these feature requests. They're also not all in the right repository.

The panel repository gets feature requests for the panel.
The coterm repository gets feature requests for coterm.
