### ISSUE TITLE
sync available backups from proxmox

### ISSUE THREAD

**Issue by D0ublek1ll** [Performave/convoy#93]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When a backup is made from the proxmox side it currently does not appear in the convoy panel.

In usecases where proxmox runs scheduled backups it would be useful to show these in the panel and allow the restoration of such backups.

Alternatively a backup schedule/rotation feature could be created in the panel.

### Describe the solution you'd like.

A feature that imports available backups from proxmox and shows them in convoy panel to allow restoration from the convoy panel.

**Comment by ericwang401** [comment]
This isn't something I'm interested in implementing at the moment. Convoy is regarded as the authoritative source in much of the design.

**Comment by D0ublek1ll** [comment]
> This isn't something I'm interested in implementing at the moment. Convoy is regarded as the authoritative source in much of the design.

I think a backup scheduler would be just as good. As long as there is a way to do automated recurring backups.
The reason why I think importing pre-existing backups from proxmox and making them available for restore trough Convoy is the prefered solution is because a lot of hosting companies will just setup blanket backup policies for all vm's if they offer the feature.

**Comment by dakser** [comment]
Hi, I agree with that "a lot of hosting companies will just setup blanket backup policies for all vm's if they offer the feature", I hope it could be implemented.
