### ISSUE TITLE
import vm feature

### ISSUE THREAD

**Issue by D0ublek1ll** [Performave/convoy#94]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A secondary workflow for creating pre-existing vm's (based on ID) into convoy panel

### Describe the solution you'd like.

A workflow to import pre-existing VM's and their configuration into convoy panel based on their ID's.
Automatically importing the current hardware specs as currently used.

Additionally it would be useful to do this in bulk.

**Comment by ericwang401** [comment]
Not going to work on this since I feel like this will cause more trouble for me than any advantage from implementing this. I feel like the vast majority of people configure their VMs in various ways that I cannot fully cover. It would sort of be like a nightmare for me :(
