### ISSUE TITLE
OIDC/saml

### ISSUE THREAD

**Issue by astromandev** [Performave/convoy#98]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Feature to allow users to login using a custom SAML and/or OIDC provider.

### Describe the solution you'd like.

This would make it possible to use an existing central userbackend (Authentik, Active Directory, Keycloak etc.) instead of having to provision new users manually in Convoy.

**Comment by ericwang401** [comment]
Not exactly a priority at the moment, but it would be helpful if you could do a couple of things for me.

1. Research difference between OIDC, OAuth, and SAML.
2. How would user sync work? Suppose a user was deleted in your central backend. What should Convoy do with the user it created too? And how would the central user backend communicate the changes to Convoy?
3. Building off of above. I don't know if these providers have a name field, but suppose they do and a user changes them in the central user backend. Is there something in the standard for these providers to communicate changes?

**Comment by ericwang401** [comment]
Doesn't seem like those questions were ever answered. This feature won't be planned.
